/* eslint-disable @next/next/no-head-element */
 // import { Inter } from 'next/font/google'
 
import SideBar from './SideBar'

// const inter = Inter({ subsets: ['latin'] })
 const metadata = {
  title: 'Ntwari Ashimwe Fiacre Portfolio',
  description: 'Generated by Ntwari Ashimwe Fiacre',
}

export default function RootLayout({ children }) {
  return (
    <div className="">
      {/* <head>
        <title>Ntwari Fiacre portfolio</title>
        <metadata name='decsription' content='generated by Ntwari Ashimwe Fiacre'/>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head> */}
    <div className="flex">
      <SideBar />
      <main className="w-screen">
        {children}
      </main>
    </div>
    </div>
  )
}
