 // import { Inter } from 'next/font/google'
 
import SideBar from './SideBar'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Ntwari Ashimwe Fiacre Portfolio',
//   description: 'Generated by Ntwari Ashimwe Fiacre',
// }

export default function RootLayout({ children }) {
  return (
    <div className="flex">
      <SideBar />
      <main className="w-screen">
        {children}
      </main>
    </div>
  )
}
